"""Export the KENNETH bekantan into the app.

Usage: python docs/brand/make_mascot.py <set folder> [repo root]

The set is made outside the repo (an image model, prompts kept with the brand kit): one
transparent PNG per pose, about 1254 px, plus a square avatar on solid cornflower. Each pose
used by the app is cropped to the character, its faint edge haze is cleared, and it is saved
as public/mascot/<name>.webp at 480 px on its long side, enough for a 160 px figure on a 3x
screen. The peek keeps its flat bottom edge, which sits on the edge of a card in the app.
src/data/mascot.ts is generated with every file's size; edit the table here, not there.
"""
import sys
from pathlib import Path

from PIL import Image

SET = Path(sys.argv[1])
ROOT = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parents[2]
OUT = ROOT / 'public' / 'mascot'
TS = ROOT / 'src' / 'data' / 'mascot.ts'
LONG = 480
AVATAR = 128

# App name, source file in the set. Add a row to bring another pose into the app.
POSES = [
    ('hello', '01-hello'),
    ('yay', '03-yay'),
    ('waiting', '04-waiting'),
    ('looking', '05-looking'),
    ('sleepy', '07-sleepy'),
    ('thinking', '09-thinking'),
    ('peek', '14-peek-bottom'),
]


def cutout(name: str, src: str) -> Image.Image:
    img = Image.open(SET / f'{src}.png').convert('RGBA')
    # The generator leaves a faint haze around some figures (the peek's bottom edge most of all). Clear it, so the
    # crop hugs the character and nothing shows as a smudge on a colored card.
    alpha = img.getchannel('A').point(lambda a: 0 if a < 16 else a)
    img.putalpha(alpha)
    left, top, right, bottom = alpha.getbbox()
    pad = round(0.02 * max(right - left, bottom - top))
    # The peek is cut flat at the bottom on purpose: no padding there, so that edge lands on the card's edge.
    box = (max(0, left - pad), max(0, top - pad), min(img.width, right + pad), bottom if name == 'peek' else min(img.height, bottom + pad))
    img = img.crop(box)
    scale = LONG / max(img.size)
    return img.resize((round(img.width * scale), round(img.height * scale)), Image.LANCZOS)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    sizes = {}
    for name, src in POSES:
        img = cutout(name, src)
        img.save(OUT / f'{name}.webp', 'WEBP', quality=86, method=6)
        sizes[name] = img.size
    # The avatar shows up as small as a 22 px circle in a toast, so it keeps the face and drops the shoulders.
    avatar = Image.open(SET / '10-avatar.png').convert('RGB')
    w, h = avatar.size
    avatar = avatar.crop((round(0.14 * w), round(0.06 * h), round(0.86 * w), round(0.78 * h))).resize((AVATAR, AVATAR), Image.LANCZOS)
    avatar.save(OUT / 'avatar.webp', 'WEBP', quality=86, method=6)
    sizes['avatar'] = avatar.size

    lines = [
        '// Generated by docs/brand/make_mascot.py from the bekantan set. Edit the table there, not here.',
        '',
        f"export type MascotArt = {' | '.join(repr(n) for n in sizes)}",
        '',
        '/** Pixel size of each file in public/mascot, so an image holds its box before it loads. */',
        'export const MASCOT_ART: Record<MascotArt, { w: number; h: number }> = {',
        *(f'  {n}: {{ w: {w}, h: {h} }},' for n, (w, h) in sizes.items()),
        '}',
        '',
    ]
    TS.write_text('\n'.join(lines).replace('"', "'"), encoding='utf-8', newline='\n')
    total = sum((OUT / f'{n}.webp').stat().st_size for n in sizes)
    print(f'{len(sizes)} files, {total // 1024} KB in {OUT}')
    for n, (w, h) in sizes.items():
        print(f'  {n}: {w} x {h}')


if __name__ == '__main__':
    main()
