// Generated by docs/brand/make_mascot.py from the bekantan set. Edit the table there, not here.

export type MascotArt = 'hello' | 'yay' | 'waiting' | 'looking' | 'sleepy' | 'thinking' | 'peek' | 'avatar'

/** Pixel size of each file in public/mascot, so an image holds its box before it loads. */
export const MASCOT_ART: Record<MascotArt, { w: number; h: number }> = {
  hello: { w: 415, h: 480 },
  yay: { w: 470, h: 480 },
  waiting: { w: 442, h: 480 },
  looking: { w: 431, h: 480 },
  sleepy: { w: 441, h: 480 },
  thinking: { w: 358, h: 480 },
  peek: { w: 480, h: 335 },
  avatar: { w: 128, h: 128 },
}
